easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\AppEntity\CommunityGroup
        - App\Entity\AppEntity\Ethnicity
        - App\Entity\AppEntity\MaritalStatus
        - App\Entity\AppEntity\Morphology
        - App\Entity\AppEntity\SexualPosition
#        - App\Entity\User
